"""Initial migration.

Revision ID: ed79baacb23f
Revises: 
Create Date: 2024-10-12 14:33:36.696310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed79baacb23f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=True))
        batch_op.drop_column('passowrd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passowrd', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
